///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ApiResponseData {
/*
{
  "id": "1",
  "customers_id": "69",
  "order_status": "8",
  "payment_type": "COD",
  "added_on": "2022-07-18 04:36:45",
  "order_id": null,
  "is_cancel": "0",
  "addressid": "0",
  "transactionid": "0",
  "total_amt": "870",
  "subtotal": "6120",
  "store_discount": null,
  "shippingcharge": "0",
  "lastmodifydt": "2022-08-08 01:59:37",
  "orders_status": "Pick Up ",
  "remarks": "When Store Assing the order to Delivery Boy, It is by UDF ",
  "entrydt": "2022-06-09 18:22:21",
  "currierboy_id": "2",
  "store_id": "1",
  "entryat": "2022-07-18 04:38:02",
  "order_status_id": "8",
  "entrytm": null,
  "order_details_id": "202",
  "orders_id": "106",
  "product_id": "94",
  "products_attr_id": "93",
  "price": "115",
  "o_qty": "4",
  "random_orderid": "RM22071916",
  "cost": "109.5",
  "vendor_status": "1",
  "status": "1",
  "currier_id": null,
  "des_id": null,
  "current_comissin_percenatge": null,
  "total_purchase_amt_item": null,
  "total_order_amt": null,
  "total_profit_amount_order": null,
  "comission_amount": null,
  "role": "4",
  "u_id": "69",
  "custgen_id": "RC2200069",
  "u_name": "Raghunath kumar",
  "u_pass": "827ccb0eea8a706c4c34a16891f84e7b",
  "u_phone": "9570313035",
  "u_email": "raghunath@gmail.com",
  "u_address": "",
  "u_status": "1",
  "created": "2022-07-18 01:24:22",
  "modified": "2022-07-18 01:24:22",
  "introducer_code": "",
  "is_apply_suvidhacard": "0",
  "addresstype": "",
  "storename": "Rasaya Store Gopalpur",
  "storeaddress": " Gopalpur",
  "state": "5",
  "district": " 6556",
  "assembly": "156",
  "panchayat": " 7",
  "pincode": "841425",
  "authorisepersonname": "Bablu Kumar",
  "storepersonmobile": "8340371787",
  "authorisepersonemail": "oyemartrupans@gmail.com",
  "password": "bablu211695",
  "isdefaultstore": "1",
  "ordercount": "2"
}
*/

  String? id;
  String? customersId;
  String? orderStatus;
  String? paymentType;
  String? addedOn;
  String? orderId;
  String? isCancel;
  String? addressid;
  String? transactionid;
  String? totalAmt;
  String? subtotal;
  String? storeDiscount;
  String? shippingcharge;
  String? lastmodifydt;
  String? ordersStatus;
  String? remarks;
  String? entrydt;
  String? currierboyId;
  String? storeId;
  String? entryat;
  String? orderStatusId;
  String? entrytm;
  String? orderDetailsId;
  String? ordersId;
  String? productId;
  String? productsAttrId;
  String? price;
  String? oQty;
  String? randomOrderid;
  String? cost;
  String? vendorStatus;
  String? status;
  String? currierId;
  String? desId;
  String? currentComissinPercenatge;
  String? totalPurchaseAmtItem;
  String? totalOrderAmt;
  String? totalProfitAmountOrder;
  String? comissionAmount;
  String? role;
  String? uId;
  String? custgenId;
  String? uName;
  String? uPass;
  String? uPhone;
  String? uEmail;
  String? uAddress;
  String? uStatus;
  String? created;
  String? modified;
  String? introducerCode;
  String? isApplySuvidhacard;
  String? addresstype;
  String? storename;
  String? storeaddress;
  String? state;
  String? district;
  String? assembly;
  String? panchayat;
  String? pincode;
  String? authorisepersonname;
  String? storepersonmobile;
  String? authorisepersonemail;
  String? password;
  String? isdefaultstore;
  String? ordercount;

  ApiResponseData({
    this.id,
    this.customersId,
    this.orderStatus,
    this.paymentType,
    this.addedOn,
    this.orderId,
    this.isCancel,
    this.addressid,
    this.transactionid,
    this.totalAmt,
    this.subtotal,
    this.storeDiscount,
    this.shippingcharge,
    this.lastmodifydt,
    this.ordersStatus,
    this.remarks,
    this.entrydt,
    this.currierboyId,
    this.storeId,
    this.entryat,
    this.orderStatusId,
    this.entrytm,
    this.orderDetailsId,
    this.ordersId,
    this.productId,
    this.productsAttrId,
    this.price,
    this.oQty,
    this.randomOrderid,
    this.cost,
    this.vendorStatus,
    this.status,
    this.currierId,
    this.desId,
    this.currentComissinPercenatge,
    this.totalPurchaseAmtItem,
    this.totalOrderAmt,
    this.totalProfitAmountOrder,
    this.comissionAmount,
    this.role,
    this.uId,
    this.custgenId,
    this.uName,
    this.uPass,
    this.uPhone,
    this.uEmail,
    this.uAddress,
    this.uStatus,
    this.created,
    this.modified,
    this.introducerCode,
    this.isApplySuvidhacard,
    this.addresstype,
    this.storename,
    this.storeaddress,
    this.state,
    this.district,
    this.assembly,
    this.panchayat,
    this.pincode,
    this.authorisepersonname,
    this.storepersonmobile,
    this.authorisepersonemail,
    this.password,
    this.isdefaultstore,
    this.ordercount,
  });
  ApiResponseData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    customersId = json['customers_id']?.toString();
    orderStatus = json['order_status']?.toString();
    paymentType = json['payment_type']?.toString();
    addedOn = json['added_on']?.toString();
    orderId = json['order_id']?.toString();
    isCancel = json['is_cancel']?.toString();
    addressid = json['addressid']?.toString();
    transactionid = json['transactionid']?.toString();
    totalAmt = json['total_amt']?.toString();
    subtotal = json['subtotal']?.toString();
    storeDiscount = json['store_discount']?.toString();
    shippingcharge = json['shippingcharge']?.toString();
    lastmodifydt = json['lastmodifydt']?.toString();
    ordersStatus = json['orders_status']?.toString();
    remarks = json['remarks']?.toString();
    entrydt = json['entrydt']?.toString();
    currierboyId = json['currierboy_id']?.toString();
    storeId = json['store_id']?.toString();
    entryat = json['entryat']?.toString();
    orderStatusId = json['order_status_id']?.toString();
    entrytm = json['entrytm']?.toString();
    orderDetailsId = json['order_details_id']?.toString();
    ordersId = json['orders_id']?.toString();
    productId = json['product_id']?.toString();
    productsAttrId = json['products_attr_id']?.toString();
    price = json['price']?.toString();
    oQty = json['o_qty']?.toString();
    randomOrderid = json['random_orderid']?.toString();
    cost = json['cost']?.toString();
    vendorStatus = json['vendor_status']?.toString();
    status = json['status']?.toString();
    currierId = json['currier_id']?.toString();
    desId = json['des_id']?.toString();
    currentComissinPercenatge = json['current_comissin_percenatge']?.toString();
    totalPurchaseAmtItem = json['total_purchase_amt_item']?.toString();
    totalOrderAmt = json['total_order_amt']?.toString();
    totalProfitAmountOrder = json['total_profit_amount_order']?.toString();
    comissionAmount = json['comission_amount']?.toString();
    role = json['role']?.toString();
    uId = json['u_id']?.toString();
    custgenId = json['custgen_id']?.toString();
    uName = json['u_name']?.toString();
    uPass = json['u_pass']?.toString();
    uPhone = json['u_phone']?.toString();
    uEmail = json['u_email']?.toString();
    uAddress = json['u_address']?.toString();
    uStatus = json['u_status']?.toString();
    created = json['created']?.toString();
    modified = json['modified']?.toString();
    introducerCode = json['introducer_code']?.toString();
    isApplySuvidhacard = json['is_apply_suvidhacard']?.toString();
    addresstype = json['addresstype']?.toString();
    storename = json['storename']?.toString();
    storeaddress = json['storeaddress']?.toString();
    state = json['state']?.toString();
    district = json['district']?.toString();
    assembly = json['assembly']?.toString();
    panchayat = json['panchayat']?.toString();
    pincode = json['pincode']?.toString();
    authorisepersonname = json['authorisepersonname']?.toString();
    storepersonmobile = json['storepersonmobile']?.toString();
    authorisepersonemail = json['authorisepersonemail']?.toString();
    password = json['password']?.toString();
    isdefaultstore = json['isdefaultstore']?.toString();
    ordercount = json['ordercount']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['customers_id'] = customersId;
    data['order_status'] = orderStatus;
    data['payment_type'] = paymentType;
    data['added_on'] = addedOn;
    data['order_id'] = orderId;
    data['is_cancel'] = isCancel;
    data['addressid'] = addressid;
    data['transactionid'] = transactionid;
    data['total_amt'] = totalAmt;
    data['subtotal'] = subtotal;
    data['store_discount'] = storeDiscount;
    data['shippingcharge'] = shippingcharge;
    data['lastmodifydt'] = lastmodifydt;
    data['orders_status'] = ordersStatus;
    data['remarks'] = remarks;
    data['entrydt'] = entrydt;
    data['currierboy_id'] = currierboyId;
    data['store_id'] = storeId;
    data['entryat'] = entryat;
    data['order_status_id'] = orderStatusId;
    data['entrytm'] = entrytm;
    data['order_details_id'] = orderDetailsId;
    data['orders_id'] = ordersId;
    data['product_id'] = productId;
    data['products_attr_id'] = productsAttrId;
    data['price'] = price;
    data['o_qty'] = oQty;
    data['random_orderid'] = randomOrderid;
    data['cost'] = cost;
    data['vendor_status'] = vendorStatus;
    data['status'] = status;
    data['currier_id'] = currierId;
    data['des_id'] = desId;
    data['current_comissin_percenatge'] = currentComissinPercenatge;
    data['total_purchase_amt_item'] = totalPurchaseAmtItem;
    data['total_order_amt'] = totalOrderAmt;
    data['total_profit_amount_order'] = totalProfitAmountOrder;
    data['comission_amount'] = comissionAmount;
    data['role'] = role;
    data['u_id'] = uId;
    data['custgen_id'] = custgenId;
    data['u_name'] = uName;
    data['u_pass'] = uPass;
    data['u_phone'] = uPhone;
    data['u_email'] = uEmail;
    data['u_address'] = uAddress;
    data['u_status'] = uStatus;
    data['created'] = created;
    data['modified'] = modified;
    data['introducer_code'] = introducerCode;
    data['is_apply_suvidhacard'] = isApplySuvidhacard;
    data['addresstype'] = addresstype;
    data['storename'] = storename;
    data['storeaddress'] = storeaddress;
    data['state'] = state;
    data['district'] = district;
    data['assembly'] = assembly;
    data['panchayat'] = panchayat;
    data['pincode'] = pincode;
    data['authorisepersonname'] = authorisepersonname;
    data['storepersonmobile'] = storepersonmobile;
    data['authorisepersonemail'] = authorisepersonemail;
    data['password'] = password;
    data['isdefaultstore'] = isdefaultstore;
    data['ordercount'] = ordercount;
    return data;
  }
}

class ApiResponse {
/*
{
  "status": 1,
  "message": "Pick up order",
  "data": [
    {
      "id": "1",
      "customers_id": "69",
      "order_status": "8",
      "payment_type": "COD",
      "added_on": "2022-07-18 04:36:45",
      "order_id": null,
      "is_cancel": "0",
      "addressid": "0",
      "transactionid": "0",
      "total_amt": "870",
      "subtotal": "6120",
      "store_discount": null,
      "shippingcharge": "0",
      "lastmodifydt": "2022-08-08 01:59:37",
      "orders_status": "Pick Up ",
      "remarks": "When Store Assing the order to Delivery Boy, It is by UDF ",
      "entrydt": "2022-06-09 18:22:21",
      "currierboy_id": "2",
      "store_id": "1",
      "entryat": "2022-07-18 04:38:02",
      "order_status_id": "8",
      "entrytm": null,
      "order_details_id": "202",
      "orders_id": "106",
      "product_id": "94",
      "products_attr_id": "93",
      "price": "115",
      "o_qty": "4",
      "random_orderid": "RM22071916",
      "cost": "109.5",
      "vendor_status": "1",
      "status": "1",
      "currier_id": null,
      "des_id": null,
      "current_comissin_percenatge": null,
      "total_purchase_amt_item": null,
      "total_order_amt": null,
      "total_profit_amount_order": null,
      "comission_amount": null,
      "role": "4",
      "u_id": "69",
      "custgen_id": "RC2200069",
      "u_name": "Raghunath kumar",
      "u_pass": "827ccb0eea8a706c4c34a16891f84e7b",
      "u_phone": "9570313035",
      "u_email": "raghunath@gmail.com",
      "u_address": "",
      "u_status": "1",
      "created": "2022-07-18 01:24:22",
      "modified": "2022-07-18 01:24:22",
      "introducer_code": "",
      "is_apply_suvidhacard": "0",
      "addresstype": "",
      "storename": "Rasaya Store Gopalpur",
      "storeaddress": " Gopalpur",
      "state": "5",
      "district": " 6556",
      "assembly": "156",
      "panchayat": " 7",
      "pincode": "841425",
      "authorisepersonname": "Bablu Kumar",
      "storepersonmobile": "8340371787",
      "authorisepersonemail": "oyemartrupans@gmail.com",
      "password": "bablu211695",
      "isdefaultstore": "1",
      "ordercount": "2"
    }
  ]
}
*/

  int? status;
  String? message;
  List<ApiResponseData?>? data;

  ApiResponse({
    this.status,
    this.message,
    this.data,
  });
  ApiResponse.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toInt();
    message = json['message']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ApiResponseData>[];
      v.forEach((v) {
        arr0.add(ApiResponseData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
